package litematica

import (
	"compress/gzip"
	"encoding/binary"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/sandertv/gophertunnel/minecraft/nbt"
)

// MappingFile is the compiled Java->Bedrock block state mapping asset,
// generated by cmd/genmap from Mojang's block report and Geyser's mappings.
const MappingFile = "java_bedrock_map.nbt.gz"

// BedrockState is a Bedrock edition block state: a name plus state properties.
type BedrockState struct {
	Name   string
	States map[string]any
}

// BlockMapper resolves Java block states (as found in .litematic/.schem files)
// to Bedrock block states and their hashed network runtime IDs.
type BlockMapper struct {
	entries map[string]BedrockState
	airRID  uint32
}

// LoadMapper reads the mapping asset from the working directory.
func LoadMapper() (*BlockMapper, error) {
	f, err := os.Open(MappingFile)
	if err != nil {
		return nil, fmt.Errorf("open %v: %w", MappingFile, err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return nil, fmt.Errorf("gunzip %v: %w", MappingFile, err)
	}
	var root struct {
		JavaVersion string         `nbt:"java_version"`
		Entries     map[string]any `nbt:"entries"`
	}
	if err := nbt.NewDecoderWithEncoding(gz, nbt.LittleEndian).Decode(&root); err != nil {
		return nil, fmt.Errorf("decode %v: %w", MappingFile, err)
	}
	m := &BlockMapper{entries: make(map[string]BedrockState, len(root.Entries))}
	for k, v := range root.Entries {
		e, ok := v.(map[string]any)
		if !ok {
			continue
		}
		name, _ := e["n"].(string)
		states, _ := e["s"].(map[string]any)
		m.entries[k] = BedrockState{Name: name, States: states}
	}
	m.airRID = HashBlock("minecraft:air", nil)
	return m, nil
}

// Len returns the number of mapping entries loaded.
func (m *BlockMapper) Len() int { return len(m.entries) }

// AirRID returns the hashed runtime ID of minecraft:air.
func (m *BlockMapper) AirRID() uint32 { return m.airRID }

// Lookup resolves a Java block (name plus properties) to a Bedrock state.
// If the exact state is unknown, it falls back to the block's default state.
func (m *BlockMapper) Lookup(name string, props map[string]string) (BedrockState, bool) {
	if e, ok := m.entries[CanonicalState(name, props)]; ok {
		return e, true
	}
	// Fallback: default state of the block, keyed by bare name.
	if e, ok := m.entries[normalizeName(name)]; ok {
		return e, true
	}
	return BedrockState{}, false
}

// CanonicalState builds the canonical key for a Java block state:
// "minecraft:name[prop=value,...]" with properties sorted alphabetically,
// or just "minecraft:name" when there are no properties.
func CanonicalState(name string, props map[string]string) string {
	name = normalizeName(name)
	if len(props) == 0 {
		return name
	}
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString(name)
	b.WriteByte('[')
	for i, k := range keys {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(props[k])
	}
	b.WriteByte(']')
	return b.String()
}

func normalizeName(name string) string {
	if !strings.Contains(name, ":") {
		return "minecraft:" + name
	}
	return name
}

// HashBlock computes the hashed block network runtime ID for a Bedrock block
// state, as used by the client when StartGame's UseBlockNetworkIDHashes is
// set: FNV-1a (32-bit) over a little-endian NBT compound of the form
// {name: <name>, states: {...}} with state keys sorted alphabetically.
func HashBlock(name string, states map[string]any) uint32 {
	if name == "minecraft:unknown" {
		return 0xfffffffe
	}

	keys := make([]string, 0, len(states))
	for k := range states {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var data []byte
	writeString := func(str string) {
		data = binary.LittleEndian.AppendUint16(data, uint16(len(str)))
		data = append(data, str...)
	}

	data = append(data, 10, 0, 0) // root compound, empty name

	data = append(data, 8) // tag string
	writeString("name")
	writeString(name)

	data = append(data, 10) // tag compound
	writeString("states")
	for _, k := range keys {
		switch v := states[k].(type) {
		case string:
			data = append(data, 8)
			writeString(k)
			writeString(v)
		case uint8:
			data = append(data, 1)
			writeString(k)
			data = append(data, v)
		case int8:
			data = append(data, 1)
			writeString(k)
			data = append(data, byte(v))
		case bool:
			b := byte(0)
			if v {
				b = 1
			}
			data = append(data, 1)
			writeString(k)
			data = append(data, b)
		case uint16:
			data = append(data, 2)
			writeString(k)
			data = binary.LittleEndian.AppendUint16(data, v)
		case int16:
			data = append(data, 2)
			writeString(k)
			data = binary.LittleEndian.AppendUint16(data, uint16(v))
		case uint32:
			data = append(data, 3)
			writeString(k)
			data = binary.LittleEndian.AppendUint32(data, v)
		case int32:
			data = append(data, 3)
			writeString(k)
			data = binary.LittleEndian.AppendUint32(data, uint32(v))
		default:
			// Unsupported state type; encode nothing for it.
		}
	}
	data = append(data, 0, 0) // end states, end root

	return fnv1a32(data)
}

func fnv1a32(data []byte) uint32 {
	const (
		offset = 0x811c9dc5
		prime  = 0x01000193
	)
	h := uint32(offset)
	for _, b := range data {
		h ^= uint32(b)
		h *= prime
	}
	return h
}
